import type { RagComparisonData } from "@/types/curation";

/**
 * Mock evaluation datasets available for selection.
 * Will be replaced with real API calls later.
 */
export const MOCK_DATASETS = [
  {
    id: "eval-001",
    name: "Enterprise Policy QA",
    description: "50 questions over internal HR & compliance documents",
    query_count: 50,
    created_at: "2026-03-28T14:00:00Z",
  },
  {
    id: "eval-002",
    name: "Biomedical Literature",
    description: "40 questions over PubMed abstracts on drug interactions",
    query_count: 40,
    created_at: "2026-03-25T10:30:00Z",
  },
];

export function getMockRagComparison(datasetId: string): RagComparisonData {
  if (datasetId === "eval-002") return BIOMEDICAL_DATA;
  return ENTERPRISE_DATA;
}

/* ── Enterprise Policy QA dataset ────────────────────── */

const ENTERPRISE_DATA: RagComparisonData = {
  dataset: MOCK_DATASETS[0],
  graph_rag_summary: {
    answer_faithfulness: 0.91,
    answer_relevance: 0.88,
    context_precision: 0.85,
    context_recall: 0.92,
    avg_latency_ms: 2340,
    avg_tokens_used: 1820,
    avg_cost_per_query: 0.0073,
  },
  vector_rag_summary: {
    answer_faithfulness: 0.78,
    answer_relevance: 0.74,
    context_precision: 0.71,
    context_recall: 0.68,
    avg_latency_ms: 1450,
    avg_tokens_used: 1420,
    avg_cost_per_query: 0.0052,
  },
  query_type_breakdown: [
    { query_type: "Multi-Hop", graph_avg_score: 0.94, vector_avg_score: 0.58, count: 12 },
    { query_type: "Factual", graph_avg_score: 0.87, vector_avg_score: 0.84, count: 15 },
    { query_type: "Aggregation", graph_avg_score: 0.92, vector_avg_score: 0.61, count: 8 },
    { query_type: "Comparison", graph_avg_score: 0.89, vector_avg_score: 0.66, count: 9 },
    { query_type: "Temporal", graph_avg_score: 0.85, vector_avg_score: 0.53, count: 6 },
  ],
  win_loss: { graph_wins: 34, vector_wins: 8, ties: 8 },
  queries: [
    {
      id: "q-001",
      query: "What is the maximum parental leave allowed if the employee has been at the company for over 2 years and is in a management role?",
      query_type: "multi_hop",
      graph_rag: {
        answer: "Employees in management roles with over 2 years of tenure are entitled to 16 weeks of paid parental leave, per Section 4.2 of the Benefits Policy, cross-referenced with the Management Tier table in Appendix B.",
        context_snippets: [
          "Section 4.2: Parental leave for employees with 2+ years tenure is 16 weeks paid.",
          "Appendix B — Management Tier: All management roles receive full benefits as per Section 4.",
        ],
        faithfulness: 0.96,
        relevance: 0.95,
        context_precision: 0.92,
        context_recall: 0.97,
        latency_ms: 2580,
        tokens_used: 1950,
      },
      vector_rag: {
        answer: "Parental leave is typically 12 weeks. Employees with longer tenure may qualify for extended leave per company policy.",
        context_snippets: [
          "Section 4.1: Standard parental leave is 12 weeks paid for all full-time employees.",
          "Section 3.7: Tenure-based benefits are reviewed annually.",
        ],
        faithfulness: 0.72,
        relevance: 0.60,
        context_precision: 0.55,
        context_recall: 0.48,
        latency_ms: 1320,
        tokens_used: 1380,
      },
      winner: "graph",
      ground_truth: "16 weeks paid parental leave for management roles with 2+ years tenure (Section 4.2 + Appendix B).",
    },
    {
      id: "q-002",
      query: "What is the company's expense reimbursement limit for domestic travel?",
      query_type: "factual",
      graph_rag: {
        answer: "The domestic travel expense reimbursement limit is $250/day for lodging and $75/day for meals, as stated in the Travel Policy Section 2.1.",
        context_snippets: [
          "Travel Policy Section 2.1: Domestic travel — lodging $250/day, meals $75/day.",
        ],
        faithfulness: 0.95,
        relevance: 0.94,
        context_precision: 0.96,
        context_recall: 0.93,
        latency_ms: 1890,
        tokens_used: 1540,
      },
      vector_rag: {
        answer: "Domestic travel reimbursement covers up to $250/day for lodging and $75/day for meals per the Travel Policy.",
        context_snippets: [
          "Travel Policy Section 2.1: Domestic travel — lodging $250/day, meals $75/day.",
          "Travel Policy Section 2.3: All receipts must be submitted within 30 days.",
        ],
        faithfulness: 0.94,
        relevance: 0.93,
        context_precision: 0.91,
        context_recall: 0.90,
        latency_ms: 1180,
        tokens_used: 1320,
      },
      winner: "tie",
      ground_truth: "$250/day lodging, $75/day meals for domestic travel (Travel Policy Section 2.1).",
    },
    {
      id: "q-003",
      query: "How many different leave types mention a waiting period, and what are the shortest and longest waiting periods?",
      query_type: "aggregation",
      graph_rag: {
        answer: "Four leave types have waiting periods: Short-term disability (7 days), FMLA (30 days employment), Sabbatical (5 years tenure), and Extended Medical (90 days). The shortest is 7 days (short-term disability) and the longest is 5 years (sabbatical).",
        context_snippets: [
          "Section 5.1: Short-term disability — 7-day waiting period.",
          "Section 5.3: FMLA — requires 30 days of employment.",
          "Section 6.2: Sabbatical — available after 5 years of continuous service.",
          "Section 5.4: Extended medical leave — 90-day employment prerequisite.",
        ],
        faithfulness: 0.94,
        relevance: 0.96,
        context_precision: 0.90,
        context_recall: 0.95,
        latency_ms: 2810,
        tokens_used: 2150,
      },
      vector_rag: {
        answer: "Several leave types have waiting periods. Short-term disability requires a 7-day waiting period, and FMLA requires 30 days of employment.",
        context_snippets: [
          "Section 5.1: Short-term disability — 7-day waiting period.",
          "Section 5.3: FMLA — requires 30 days of employment.",
        ],
        faithfulness: 0.81,
        relevance: 0.55,
        context_precision: 0.70,
        context_recall: 0.45,
        latency_ms: 1510,
        tokens_used: 1400,
      },
      winner: "graph",
      ground_truth: "4 leave types: Short-term disability (7 days), FMLA (30 days), Extended Medical (90 days), Sabbatical (5 years). Shortest: 7 days, Longest: 5 years.",
    },
    {
      id: "q-004",
      query: "Compare the health insurance coverage for full-time vs part-time employees.",
      query_type: "comparison",
      graph_rag: {
        answer: "Full-time employees receive 100% employer-paid premiums for individual plans and 75% for family plans. Part-time employees (20+ hrs/week) receive 50% employer-paid for individual plans only; family plans are available at full employee cost. Dental and vision are included for full-time but optional add-ons for part-time.",
        context_snippets: [
          "Benefits Section 3.1: Full-time — 100% individual, 75% family premium coverage.",
          "Benefits Section 3.2: Part-time (20+ hrs) — 50% individual premium only.",
          "Benefits Section 3.4: Dental/vision included full-time, optional part-time.",
        ],
        faithfulness: 0.93,
        relevance: 0.92,
        context_precision: 0.88,
        context_recall: 0.94,
        latency_ms: 2450,
        tokens_used: 1980,
      },
      vector_rag: {
        answer: "Full-time employees get comprehensive health insurance with employer-paid premiums. Part-time employees may be eligible for reduced coverage.",
        context_snippets: [
          "Benefits Section 3.1: Full-time — 100% individual, 75% family premium coverage.",
          "Benefits overview: Coverage varies based on employment status.",
        ],
        faithfulness: 0.74,
        relevance: 0.62,
        context_precision: 0.60,
        context_recall: 0.52,
        latency_ms: 1380,
        tokens_used: 1350,
      },
      winner: "graph",
      ground_truth: "Full-time: 100% individual / 75% family premiums + dental/vision. Part-time (20+ hrs): 50% individual only, no family, dental/vision optional.",
    },
    {
      id: "q-005",
      query: "Has the remote work policy changed since 2024, and if so, what are the key differences?",
      query_type: "temporal",
      graph_rag: {
        answer: "Yes. The 2024 policy allowed 2 days/week remote for all roles. The 2025 revision expanded this to 3 days/week for IC roles and introduced fully-remote eligibility for employees 50+ miles from an office. Manager approval is no longer required for the standard 3-day arrangement.",
        context_snippets: [
          "Remote Policy v2024: 2 days/week remote, manager approval required.",
          "Remote Policy v2025 (effective Jan 2025): 3 days/week IC roles, no manager approval.",
          "Remote Policy v2025 Section 1.3: Fully-remote for 50+ miles from office.",
        ],
        faithfulness: 0.92,
        relevance: 0.90,
        context_precision: 0.86,
        context_recall: 0.91,
        latency_ms: 2680,
        tokens_used: 2010,
      },
      vector_rag: {
        answer: "The current remote work policy allows employees to work remotely up to 3 days per week. Some roles may qualify for fully-remote arrangements.",
        context_snippets: [
          "Remote Policy v2025: 3 days/week remote for IC roles.",
          "FAQ: Fully-remote arrangements available in certain cases.",
        ],
        faithfulness: 0.70,
        relevance: 0.50,
        context_precision: 0.55,
        context_recall: 0.42,
        latency_ms: 1290,
        tokens_used: 1280,
      },
      winner: "graph",
      ground_truth: "2024: 2 days/week + manager approval. 2025: 3 days/week for ICs (no approval), fully-remote for 50+ miles.",
    },
    {
      id: "q-006",
      query: "What is the dress code policy?",
      query_type: "factual",
      graph_rag: {
        answer: "Business casual is the standard dress code. Client-facing meetings require business formal. Casual Fridays allow jeans and sneakers.",
        context_snippets: [
          "Workplace Policy Section 7.1: Business casual standard, business formal for client meetings, casual Fridays.",
        ],
        faithfulness: 0.94,
        relevance: 0.96,
        context_precision: 0.95,
        context_recall: 0.92,
        latency_ms: 1750,
        tokens_used: 1320,
      },
      vector_rag: {
        answer: "The dress code is business casual. Business formal is required for client-facing meetings. Fridays are casual.",
        context_snippets: [
          "Workplace Policy Section 7.1: Business casual standard, business formal for client meetings, casual Fridays.",
        ],
        faithfulness: 0.95,
        relevance: 0.95,
        context_precision: 0.94,
        context_recall: 0.93,
        latency_ms: 1050,
        tokens_used: 1200,
      },
      winner: "tie",
      ground_truth: "Business casual standard; business formal for client meetings; casual Fridays.",
    },
    {
      id: "q-007",
      query: "If an engineer in the London office wants to transfer to the NYC office, what approvals are needed and how does their compensation change?",
      query_type: "multi_hop",
      graph_rag: {
        answer: "Inter-office transfers require: (1) direct manager approval, (2) receiving office head approval, (3) HR review for visa/work authorization. Compensation is adjusted to the destination city's band — NYC band is typically 15-20% higher than London for engineering roles per the Geo Pay Appendix. Relocation assistance of up to $10,000 is provided.",
        context_snippets: [
          "Transfer Policy Section 2.1: Manager + receiving office head + HR approval required.",
          "Transfer Policy Section 2.4: Visa/work authorization review for cross-border transfers.",
          "Geo Pay Appendix: NYC engineering band 15-20% above London.",
          "Relocation Policy: Up to $10,000 relocation assistance for inter-office transfers.",
        ],
        faithfulness: 0.95,
        relevance: 0.93,
        context_precision: 0.89,
        context_recall: 0.96,
        latency_ms: 2920,
        tokens_used: 2200,
      },
      vector_rag: {
        answer: "Office transfers require manager approval and HR coordination. Compensation may be adjusted based on location.",
        context_snippets: [
          "Transfer Policy Section 2.1: Manager + receiving office head + HR approval required.",
          "Compensation overview: Pay bands vary by geography.",
        ],
        faithfulness: 0.68,
        relevance: 0.52,
        context_precision: 0.50,
        context_recall: 0.38,
        latency_ms: 1400,
        tokens_used: 1350,
      },
      winner: "graph",
      ground_truth: "Approvals: manager, receiving office head, HR (visa review). NYC band is 15-20% higher. $10,000 relocation assistance.",
    },
    {
      id: "q-008",
      query: "What percentage of the training budget can be used for external conferences?",
      query_type: "factual",
      graph_rag: {
        answer: "Up to 40% of the annual $3,000 individual training budget can be allocated to external conferences, subject to manager approval at least 6 weeks in advance.",
        context_snippets: [
          "L&D Policy Section 3.2: External conferences — up to 40% of training budget, 6-week advance approval.",
          "L&D Policy Section 3.1: Annual individual training budget is $3,000.",
        ],
        faithfulness: 0.93,
        relevance: 0.91,
        context_precision: 0.90,
        context_recall: 0.94,
        latency_ms: 2100,
        tokens_used: 1650,
      },
      vector_rag: {
        answer: "External conference attendance can be covered by the training budget. Employees should consult with their manager and submit requests in advance.",
        context_snippets: [
          "L&D Policy Section 3.2: External conferences — up to 40% of training budget.",
          "L&D FAQ: Submit requests at least 4 weeks ahead.",
        ],
        faithfulness: 0.76,
        relevance: 0.70,
        context_precision: 0.72,
        context_recall: 0.65,
        latency_ms: 1220,
        tokens_used: 1300,
      },
      winner: "graph",
      ground_truth: "Up to 40% of the $3,000 annual training budget; requires manager approval 6 weeks in advance.",
    },
  ],
  index_build_cost: {
    graph_rag: { time_s: 342, cost_usd: 1.85, storage_mb: 48 },
    vector_rag: { time_s: 28, cost_usd: 0.12, storage_mb: 15 },
  },
};

/* ── Biomedical Literature dataset ───────────────────── */

const BIOMEDICAL_DATA: RagComparisonData = {
  dataset: MOCK_DATASETS[1],
  graph_rag_summary: {
    answer_faithfulness: 0.93,
    answer_relevance: 0.90,
    context_precision: 0.87,
    context_recall: 0.94,
    avg_latency_ms: 2780,
    avg_tokens_used: 2100,
    avg_cost_per_query: 0.0084,
  },
  vector_rag_summary: {
    answer_faithfulness: 0.72,
    answer_relevance: 0.68,
    context_precision: 0.64,
    context_recall: 0.59,
    avg_latency_ms: 1620,
    avg_tokens_used: 1580,
    avg_cost_per_query: 0.0058,
  },
  query_type_breakdown: [
    { query_type: "Multi-Hop", graph_avg_score: 0.96, vector_avg_score: 0.51, count: 10 },
    { query_type: "Factual", graph_avg_score: 0.89, vector_avg_score: 0.82, count: 12 },
    { query_type: "Aggregation", graph_avg_score: 0.94, vector_avg_score: 0.55, count: 7 },
    { query_type: "Comparison", graph_avg_score: 0.91, vector_avg_score: 0.62, count: 6 },
    { query_type: "Temporal", graph_avg_score: 0.88, vector_avg_score: 0.49, count: 5 },
  ],
  win_loss: { graph_wins: 30, vector_wins: 5, ties: 5 },
  queries: [
    {
      id: "bq-001",
      query: "What are the known drug interactions between Warfarin and SSRIs, and which SSRIs have the highest bleeding risk?",
      query_type: "multi_hop",
      graph_rag: {
        answer: "Warfarin interacts with all SSRIs via CYP2C9 inhibition, increasing INR and bleeding risk. Fluoxetine and fluvoxamine carry the highest risk due to strong CYP2C9/CYP1A2 inhibition. Sertraline and citalopram are considered safer alternatives with moderate monitoring.",
        context_snippets: [
          "Warfarin metabolism: primarily CYP2C9, secondarily CYP3A4.",
          "Fluoxetine: strong CYP2C9 inhibitor — contraindicated with Warfarin (Grade A evidence).",
          "Fluvoxamine: strong CYP1A2/CYP2C9 inhibitor — high bleeding risk with anticoagulants.",
          "Sertraline: weak CYP2C9 effect — preferred SSRI with Warfarin (monitor INR).",
        ],
        faithfulness: 0.97,
        relevance: 0.95,
        context_precision: 0.93,
        context_recall: 0.98,
        latency_ms: 3100,
        tokens_used: 2400,
      },
      vector_rag: {
        answer: "SSRIs can increase bleeding risk when combined with Warfarin. Patients should be monitored for signs of bleeding.",
        context_snippets: [
          "SSRIs and anticoagulants: increased bleeding risk reported in several studies.",
          "Warfarin: requires regular INR monitoring.",
        ],
        faithfulness: 0.65,
        relevance: 0.48,
        context_precision: 0.45,
        context_recall: 0.35,
        latency_ms: 1580,
        tokens_used: 1450,
      },
      winner: "graph",
      ground_truth: "All SSRIs interact with Warfarin via CYP2C9. Fluoxetine and fluvoxamine = highest bleeding risk. Sertraline/citalopram = safer alternatives with monitoring.",
    },
    {
      id: "bq-002",
      query: "What is the half-life of Metformin?",
      query_type: "factual",
      graph_rag: {
        answer: "Metformin has a plasma elimination half-life of approximately 6.2 hours. The elimination half-life in blood is approximately 17.6 hours due to partitioning into erythrocytes.",
        context_snippets: [
          "Metformin pharmacokinetics: plasma t½ = 6.2h, blood t½ = 17.6h (erythrocyte partitioning).",
        ],
        faithfulness: 0.96,
        relevance: 0.97,
        context_precision: 0.95,
        context_recall: 0.94,
        latency_ms: 2100,
        tokens_used: 1650,
      },
      vector_rag: {
        answer: "Metformin has an elimination half-life of approximately 6.2 hours in plasma.",
        context_snippets: [
          "Metformin pharmacokinetics: plasma t½ = 6.2h, blood t½ = 17.6h.",
        ],
        faithfulness: 0.93,
        relevance: 0.94,
        context_precision: 0.92,
        context_recall: 0.88,
        latency_ms: 1250,
        tokens_used: 1350,
      },
      winner: "tie",
      ground_truth: "Plasma half-life ~6.2 hours; blood half-life ~17.6 hours (erythrocyte partitioning).",
    },
  ],
  index_build_cost: {
    graph_rag: { time_s: 510, cost_usd: 2.40, storage_mb: 72 },
    vector_rag: { time_s: 35, cost_usd: 0.15, storage_mb: 22 },
  },
};
